In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.get_weights()

[array([[ 0.01472688,  1.0568362 ],
        [-0.5269417 ,  0.54076743]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.97857326],
        [ 0.8803283 ]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [np.array([[0.1,0.1],
                         [0.1,0.1 ]], dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],
                         [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32 )]

In [9]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1,L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l],1))

  return parameters

In [10]:
model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [15]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 31.9603 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.0831 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.8869 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.2015 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.8530 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 31.8122 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 30.9302 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 31.4976 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.9383 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 28.3454 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.9999 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23.5023
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 28.2266 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.6331 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 17.1989
Epoch 16/75
4/4 ━━━

In [16]:
model.get_weights()

[array([[0.3736244 , 0.3736244 ],
        [0.36556688, 0.36556688]], dtype=float32),
 array([0.27229866, 0.27229866], dtype=float32),
 array([[0.37290666],
        [0.37290666]], dtype=float32),
 array([0.2046717], dtype=float32)]

In [ ]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def linear_forward(A_prev,W,b):

  Z = np.dot(W.T,A_prev) + b

  return Z

In [ ]:
#forward propagation
def L_layer_forward(X,parameters):

  A = X
  L = len(parameters) // 2

  for l in range(1,L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ",A_prev)
    #print("W"+str(l)+": ",Wl)
    #print("b"+str(l)+": ",bl)
    #print("--"*20)

    A= linear_forward(A_prev,Wl,bl)
    #print("A"+str(l)+": ",A)
    #print("**"*20)

  return A,A_prev

student 1

In [ ]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1) #shape(no.of features , no. of training example)
y= df[['lpa']].values[0][0]

#parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [ ]:
(y- 0.32)**2

13.5424

In [ ]:
y_hat = y_hat[0][0]

In [ ]:
A1   #OUTPUT OF NEXT LEVEL NODES

array([[1.79178685],
       [1.7       ]])

In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

<ipython-input-42-f16975403a33>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-42-f16975403a33>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-42-f16975403a33>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [ ]:
parameters

{'W1': array([[0.19364654, 0.16018592],
        [0.12453612, 0.15888669]]),
 'b1': array([[0.00501549],
        [0.00490722]]),
 'W2': array([[0.20481369],
        [0.2000477 ]]),
 'b2': array([[0.21302883]])}

student 2

In [ ]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[7]
 [9]]
W1:  [[0.20702614 0.19229695]
 [0.13780345 0.19072828]]
b1:  [[0.00769141]
 [0.00756069]]
----------------------------------------
A1:  [[2.69710542]
 [3.07019385]]
****************************************
A1:  [[2.69710542]
 [3.07019385]]
W2:  [[0.2331374 ]
 [0.23118114]]
b2:  [[0.242659]]
----------------------------------------
A2:  [[1.58122605]]
****************************************


In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

<ipython-input-42-f16975403a33>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-42-f16975403a33>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-42-f16975403a33>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [ ]:
parameters

{'W1': array([[0.21906742, 0.2077786 ],
        [0.1498732 , 0.20624653]]),
 'b1': array([[0.0094116 ],
        [0.00928494]]),
 'W2': array([[0.25157899],
        [0.25217374]]),
 'b2': array([[0.25901128]])}

student 3

In [ ]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[ 6]
 [10]]
W1:  [[0.21906742 0.2077786 ]
 [0.1498732  0.20624653]]
b1:  [[0.0094116 ]
 [0.00928494]]
----------------------------------------
A1:  [[2.82254812]
 [3.31842183]]
****************************************
A1:  [[2.82254812]
 [3.31842183]]
W2:  [[0.25157899]
 [0.25217374]]
b2:  [[0.25901128]]
----------------------------------------
A2:  [[1.80592391]]
****************************************


In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

<ipython-input-42-f16975403a33>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-42-f16975403a33>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-42-f16975403a33>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [ ]:
parameters

{'W1': array([[0.22940127, 0.22500169],
        [0.16035126, 0.22370997]]),
 'b1': array([[0.0111339 ],
        [0.01103128]]),
 'W2': array([[0.26960985],
        [0.27337232]]),
 'b2': array([[0.27976047]])}

student 4

In [ ]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[ 5]
 [12]]
W1:  [[0.22940127 0.22500169]
 [0.16035126 0.22370997]]
b1:  [[0.0111339 ]
 [0.01103128]]
----------------------------------------
A1:  [[3.08235543]
 [3.82055935]]
****************************************
A1:  [[3.08235543]
 [3.82055935]]
W2:  [[0.26960985]
 [0.27337232]]
b2:  [[0.27976047]]
----------------------------------------
A2:  [[2.15522904]]
****************************************


In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

<ipython-input-42-f16975403a33>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-42-f16975403a33>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-42-f16975403a33>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [ ]:
parameters

{'W1': array([[0.23756995, 0.24460651],
        [0.16874645, 0.24385843]]),
 'b1': array([[0.01276764],
        [0.01271032]]),
 'W2': array([[0.28714704],
        [0.29510955]]),
 'b2': array([[0.30079909]])}

In [ ]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [ ]:
 # epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

   Loss = []

   for j in range(df.shape[0]):

    X = df[['cgpa','profile_score']].values[j].reshape(2,1)


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

    print('Epochs - ',i+1,'Loss - ',np.array(Loss).mean())

 parameters

Epochs -  1 Loss -  21.902399999999997
Epochs -  1 Loss -  20.967670433864114
Epochs -  1 Loss -  20.335846527832672
Epochs -  1 Loss -  19.6658119226096
Epochs -  2 Loss -  16.66649827043206
Epochs -  2 Loss -  15.974703155290406
Epochs -  2 Loss -  15.244303421817277
Epochs -  2 Loss -  14.343825738710468
Epochs -  3 Loss -  10.502455176567771
Epochs -  3 Loss -  9.683458224787497
Epochs -  3 Loss -  8.883757476299616
Epochs -  3 Loss -  7.94962559062518
Epochs -  4 Loss -  4.555832029902555
Epochs -  4 Loss -  3.9942396511539884
Epochs -  4 Loss -  3.49851001791311
Epochs -  4 Loss -  2.940707713545631
Epochs -  5 Loss -  1.3328743300105041
Epochs -  5 Loss -  1.1162161190830895
Epochs -  5 Loss -  0.9409560626728047
Epochs -  5 Loss -  0.7389393365195225


{'W1': array([[0.25996552, 0.33555727],
        [0.26931933, 0.34947978]]),
 'b1': array([[0.02437775],
        [0.02581171]]),
 'W2': array([[0.38319482],
        [0.4304424 ]]),
 'b2': array([[0.43117148]])}